const OAUTH_TOKEN_URL = '';
const TWITTER_CONSUMER_KEY = '';
const TWITTER_CONSUMER_SECRET = '';
const TWITTER_ACCESS_TOKEN = '';
const TWITTER_ACCESS_SECRET = '';
const CURRENT_USER = '';

const MYSQL_HOST = '';
const MYSQL_USER = '';
const MYSQL_PASSWORD = '';
const MYSQL_DATABASE = '';
const TOKEN_SALT = '';



const GITHUB_APP_NAME = 'QVTools';

const SERVER_PORT = 28000;

module.exports.OAUTH_TOKEN_URL = OAUTH_TOKEN_URL;
module.exports.TWITTER_CONSUMER_KEY = TWITTER_CONSUMER_KEY;
module.exports.TWITTER_CONSUMER_SECRET = TWITTER_CONSUMER_SECRET;
module.exports.TWITTER_ACCESS_TOKEN = TWITTER_ACCESS_TOKEN;
module.exports.TWITTER_ACCESS_SECRET = TWITTER_ACCESS_SECRET;
module.exports.CURRENT_USER = CURRENT_USER;

module.exports.MYSQL_HOST = MYSQL_HOST;
module.exports.MYSQL_USER = MYSQL_USER;
module.exports.MYSQL_PASSWORD = MYSQL_PASSWORD;
module.exports.MYSQL_DATABASE = MYSQL_DATABASE;
module.exports.TOKEN_SALT = TOKEN_SALT;

module.exports.GITHUB_APP_NAME = GITHUB_APP_NAME;
module.exports.GITHUB_CLIENT_ID = GITHUB_CLIENT_ID;
module.exports.GITHUB_CLIENT_SECRET = GITHUB_CLIENT_SECRET;
module.exports.SERVER_PORT = SERVER_PORT
